name: Node.js Build and Artifact Upload

on: workflow_dispatch

jobs:
  node_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Package application
        run: |
          mkdir staging
          shopt -s extglob
          cp -r !(staging) staging/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: NodePackage
          path: staging
